### ISSUE TITLE
Feature Multi-line task titles

### ISSUE THREAD

**Issue by opk12** [stride-tasks/stride#13]
No idea if this is in-scope, but what about multi-line todo's? This would even allow to repurpose the app as git-backed memo storage.

**Comment by HalidOdat** [comment]
Hi :wave: @opk12 

> No idea if this is in-scope, but what about multi-line todo's? 

The title of each tasks will stay as a single line, but I plan to add annotations on tasks that the user can add and they can be multi-line, this is where user can write notes on the task.

I have some interesting idea of an actionable annotation, like a url which makes the task go to the url when click, or an email address sends you to a mail client. Inspired by [`taskopen`](https://github.com/jschlatow/taskopen).

> This would even allow to repurpose the app as git-backed memo storage.

In the storage everything is kept as a single line (the new lines are escaped), it is very important that this property is preserved because it makes merge conflict resolution a lot easier and with the new encryption feature which is coming up in the next alpha release this is even more important.

`stride` handles merge conflicts and it's designed to be use with multiple clients in mind, it rebases (to keep the git history clean), latest task changes are taken.

**Comment by opk12** [comment]
That's a very interesting approach, it draws clear lines between the serialized form, the data structure, and the GUI metaphor.

> stride automatically handles merge conflicts and it's designed to be use with multiple stride clients in mind, it rebases (to keep the git history clean), latest task changes are taken.

That's clear. I like a lot that git is supported natively in this app. While everyone wants future-proof storage, and F-droid users are notoriously picky about vendor lock-in, git support it's a big plus and I think this is the unique tasks lists app from F-droid that can do it.

**Comment by HalidOdat** [comment]
Closing this in favor of #25 :)
