### ISSUE TITLE
Button name on long tap

### ISSUE THREAD

**Issue by opk12** [stride-tasks/stride#18]
What does the last filter icon do? Does the due date icon mean expired or today, does it include soon-to-be-due? A common pattern in Android apps is that the long tap shows a tool tip with the button name, maybe it could help in this case.

**Comment by HalidOdat** [comment]
Yeah tooltips need to added. Due to space restrictions on phones they the text is not shown, but on the desktop versions the text is visible (planned to be added in future releases).

The last two are not implemented (I'll remove them in the next release):

- Alarm are waiting tasks which are tasks that do not appear in the task list until a specified date (stuff like events that are far in the future and you don't want to see them in list constantly)
- Last icon is for recurring task.
